version: '3.2'
services:
  gw:
    build: .docker/proxy-gw
    image: oxyjs/proxy-gateway:latest
    volumes:
    - ./.docker/proxy-gw/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
  proxy:
    build:
      dockerfile: .docker/proxy-oxy/Dockerfile
      context: .
    image: oxyjs/proxy-oxy:latest
    volumes:
    - ./.docker/proxy-oxy/default.conf:/etc/nginx/conf.d/default.conf
    - ./oxy:/oxy/assets/oxy:ro
  frontend:
    image: nginx:alpine
    volumes:
    - ./app:/usr/share/nginx/html:ro
  backend:
    image: nginx:alpine
  redirect:
    build: .docker/redirect
    image: oxyjs/redirect:latest
  oxy:
    build:
      dockerfile: .docker/oxy/Dockerfile
      context: .
    image: oxyjs/oxy:latest